# -*- coding: utf-8 -*-
"""Question 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MAskAVD5F20e6dQLNxNUokOJu9PwA2Ay
"""



total_price=1200000
deposit_amount=300000
remaining_amount=total_price-deposit_amount
month=6
monthly_payment=remaining_amount/month
print("Total_Price: ",total_price,"RWF")
print("Deposit_Amount: ",deposit_amount,"RWF")
print("Remaining_Balance: ",remaining_amount,"RWF")
print("Monthly_Installment_Amount: ",monthly_payment,"RWF")

